[package]
name = "blockchain-prototype"
authors = ["Anirudh Konidala"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sha2 = "0.10.8"
ring = "0.17.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"